import os
import sys
import time
import wave

file_name = sys.argv[1]

w = wave.open(file_name, 'rb')

n = w.getnframes()
frames = w.readframes(n)

output_file = os.path.splitext(file_name)[0] + '.h'

with open(output_file, 'w') as f:
    f.write('/* Generated by converter @ {} */\n'.format(time.time()))
    f.write('\n\n')
    f.write('const uint16_t gen[] = {')
    for i in range(0, len(frames), 2):
        if (i % 20) == 0:
            f.write('\n\t')
        byte = frames[i:i+2].hex()
        f.write('0x{}, '.format(byte))
    f.write('\n};')
